version: '3.9'

services:
  db-mysql:
    image: mysql:8
    container_name: db-mysql
    volumes:
      - .data/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USER}
    networks:
      - db-mysql
    ports:
      - ${DB_PORT_EXTERNAL}:${DB_PORT_INTERNAL}
    restart: unless-stopped

networks:
  db-mysql:
    name: db-mysql
